# Generated by Django 3.2.25 on 2026-04-07 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '值班表',
                'verbose_name_plural': '值班表',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='RotaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='标识')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='说明')),
            ],
            options={
                'verbose_name': '轮值表',
                'verbose_name_plural': '轮值表',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=64, verbose_name='申请类型')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(verbose_name='结束时间')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16)),
                ('cc', models.CharField(blank=True, max_length=512, verbose_name='抄送说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='备注')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduling.dutysheet', verbose_name='值班表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignments', to=settings.AUTH_USER_MODEL, verbose_name='值班人')),
            ],
            options={
                'verbose_name': '值班排班',
                'verbose_name_plural': '值班排班',
                'ordering': ('date', 'sheet_id', 'user_id'),
            },
        ),
        migrations.CreateModel(
            name='RotaMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('status', models.CharField(choices=[('online', '在线'), ('busy', '忙碌'), ('offline', '离线')], default='online', max_length=16, verbose_name='当值状态')),
                ('active_ticket_count', models.PositiveIntegerField(default=0, verbose_name='进行中单据数')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='scheduling.rotatable', verbose_name='轮值表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rota_memberships', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '轮值成员',
                'verbose_name_plural': '轮值成员',
                'ordering': ('rota', 'sort_order', 'id'),
                'unique_together': {('rota', 'user')},
            },
        ),
    ]
