# Generated by Django 3.2.25 on 2026-04-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityRouteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('bu', 'BU'), ('control', '管控'), ('ops', '运维'), ('dev', '开发'), ('guest', '访客'), ('hcs', 'HCS')], max_length=16, verbose_name='提单人身份')),
                ('time_window', models.CharField(choices=[('day', '工作日白天'), ('night', '晚间/节假日')], max_length=16, verbose_name='时间窗口')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('duty_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_routes', to='scheduling.dutysheet', verbose_name='命中值班表')),
                ('rota_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identity_routes', to='scheduling.rotatable', verbose_name='命中轮值表')),
            ],
            options={
                'verbose_name': '身份分单路由规则',
                'verbose_name_plural': '身份分单路由规则',
                'ordering': ('priority', 'id'),
                'unique_together': {('identity', 'time_window', 'priority')},
            },
        ),
    ]
