# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=128, unique=True, verbose_name='字段编码')),
                ('field_name', models.CharField(max_length=128, verbose_name='字段名称')),
                ('field_type', models.CharField(choices=[('text', '文本'), ('date', '日期'), ('rich_text', '富文本'), ('select', '下拉'), ('doer_tag', 'Doer标注')], default='text', max_length=32, verbose_name='字段类型')),
                ('validation_json', models.JSONField(blank=True, null=True, verbose_name='校验规则')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '字段定义',
                'verbose_name_plural': '字段定义',
                'db_table': 'field_definition',
            },
        ),
        migrations.CreateModel(
            name='FieldOptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.CharField(max_length=256, verbose_name='值')),
                ('option_label', models.CharField(max_length=256, verbose_name='显示名')),
                ('order_no', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '选项项',
                'verbose_name_plural': '选项项',
                'db_table': 'field_option_item',
                'ordering': ['option_set_id', 'order_no'],
            },
        ),
        migrations.CreateModel(
            name='FieldOptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_set_code', models.CharField(max_length=64, unique=True, verbose_name='选项集编码')),
                ('option_set_name', models.CharField(max_length=128, verbose_name='选项集名称')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '字段选项集',
                'verbose_name_plural': '字段选项集',
                'db_table': 'field_option_set',
            },
        ),
        migrations.CreateModel(
            name='FieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(db_index=True, max_length=64, verbose_name='阶段编码')),
                ('rule_name', models.CharField(max_length=128, verbose_name='规则名')),
                ('condition_expr', models.TextField(blank=True, verbose_name='条件表达式')),
                ('action_expr', models.TextField(blank=True, verbose_name='动作表达式')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '字段联动规则',
                'verbose_name_plural': '字段联动规则',
                'db_table': 'field_rule',
            },
        ),
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_code', models.CharField(db_index=True, max_length=64, verbose_name='表单编码')),
                ('schema_name', models.CharField(max_length=128, verbose_name='表单名称')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('offline', '已下线')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '表单版本',
                'verbose_name_plural': '表单版本',
                'db_table': 'form_schema',
            },
        ),
        migrations.CreateModel(
            name='StageFieldBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(db_index=True, max_length=64, verbose_name='阶段编码')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='是否只读')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '阶段字段绑定',
                'verbose_name_plural': '阶段字段绑定',
                'db_table': 'stage_field_binding',
            },
        ),
        migrations.CreateModel(
            name='TicketFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(db_index=True, max_length=64, verbose_name='阶段编码')),
                ('field_code', models.CharField(db_index=True, max_length=128, verbose_name='字段编码')),
                ('field_value_text', models.TextField(blank=True, verbose_name='文本值')),
                ('field_value_json', models.JSONField(blank=True, null=True, verbose_name='结构化值')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工单字段值',
                'verbose_name_plural': '工单字段值',
                'db_table': 'ticket_field_value',
            },
        ),
    ]
