# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfieldvalue',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='ticketfieldvalue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_field_value_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagefieldbinding',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_bindings', to='form.fielddefinition'),
        ),
        migrations.AddField(
            model_name='stagefieldbinding',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_field_bindings', to='form.formschema'),
        ),
        migrations.AlterUniqueTogether(
            name='formschema',
            unique_together={('schema_code', 'version_no')},
        ),
        migrations.AddField(
            model_name='fieldrule',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='form.formschema'),
        ),
        migrations.AddField(
            model_name='fieldoptionitem',
            name='option_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='form.fieldoptionset'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='option_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_definitions', to='form.fieldoptionset'),
        ),
        migrations.AddIndex(
            model_name='ticketfieldvalue',
            index=models.Index(fields=['ticket', 'stage_code'], name='ticket_fiel_ticket__7972b3_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketfieldvalue',
            index=models.Index(fields=['ticket', 'stage_code', 'field_code'], name='ticket_fiel_ticket__786f2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stagefieldbinding',
            unique_together={('schema', 'stage_code', 'field')},
        ),
    ]
