# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='工单号')),
                ('source_type', models.CharField(choices=[('HCS', 'HCS'), ('BU', 'BU'), ('temp', '临时提单'), ('self', '运维自提单')], db_index=True, max_length=16, verbose_name='来源类型')),
                ('current_stage_code', models.CharField(db_index=True, max_length=64, verbose_name='当前阶段')),
                ('is_quality_issue', models.BooleanField(blank=True, null=True, verbose_name='是否质量问题')),
                ('is_consult_issue', models.BooleanField(blank=True, null=True, verbose_name='是否咨询问题')),
                ('issue_type', models.CharField(blank=True, choices=[('kernel', '内核'), ('control', '管控'), ('other', '其他')], db_index=True, max_length=16, verbose_name='问题类型')),
                ('priority', models.CharField(blank=True, db_index=True, max_length=16, verbose_name='优先级')),
                ('status', models.CharField(choices=[('processing', '处理中'), ('closed', '已关闭'), ('cancelled', '已取消')], db_index=True, default='processing', max_length=16, verbose_name='工单状态')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='开单时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关单时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='system.sysorggroup')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketStageDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(max_length=64, unique=True, verbose_name='阶段编码')),
                ('stage_name', models.CharField(max_length=128, verbose_name='阶段名称')),
                ('stage_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '阶段定义',
                'verbose_name_plural': '阶段定义',
                'db_table': 'ticket_stage_def',
                'ordering': ['stage_order'],
            },
        ),
        migrations.CreateModel(
            name='TicketOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(db_index=True, max_length=64, verbose_name='操作类型')),
                ('before_json', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('after_json', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_operation_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='ticket.ticket')),
            ],
            options={
                'verbose_name': '工单审计日志',
                'verbose_name_plural': '工单审计日志',
                'db_table': 'ticket_operation_log',
            },
        ),
        migrations.CreateModel(
            name='TicketAssigneeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_code', models.CharField(db_index=True, max_length=64, verbose_name='阶段')),
                ('assign_type', models.CharField(choices=[('auto', '自动分单'), ('manual', '手工'), ('special', '专项'), ('control', '管控'), ('designated', '指定人员')], default='auto', max_length=16, verbose_name='分配类型')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('assignee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_assignee_histories', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_histories', to='ticket.ticket')),
            ],
            options={
                'verbose_name': '处理人历史',
                'verbose_name_plural': '处理人历史',
                'db_table': 'ticket_assignee_history',
            },
        ),
        migrations.CreateModel(
            name='TicketTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage_code', models.CharField(blank=True, max_length=64, verbose_name='来源阶段')),
                ('to_stage_code', models.CharField(db_index=True, max_length=64, verbose_name='目标阶段')),
                ('action_code', models.CharField(db_index=True, max_length=32, verbose_name='动作')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transitions_from_assignee', to=settings.AUTH_USER_MODEL)),
                ('operator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_transitions_operated', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='ticket.ticket')),
                ('to_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_transitions_to_assignee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '流转记录',
                'verbose_name_plural': '流转记录',
                'db_table': 'ticket_transition',
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='ticket_tran_ticket__c324e6_idx'), models.Index(fields=['to_stage_code', 'created_at'], name='ticket_tran_to_stag_025585_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['current_stage_code', 'current_assignee', 'status'], name='ticket_current_d61031_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='ticket_created_807d9e_idx'),
        ),
    ]
