# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='显示名')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='手机号')),
                ('user_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], db_index=True, default='active', max_length=16, verbose_name='账号状态')),
                ('is_admin', models.BooleanField(default=False, verbose_name='业务管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'sys_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SysOrgGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=64, unique=True, verbose_name='组编码')),
                ('group_name', models.CharField(max_length=128, verbose_name='组名称')),
                ('group_type', models.CharField(choices=[('kernel', '内核'), ('control', '管控'), ('public_cloud', '公有云'), ('special', '专项')], default='kernel', max_length=32, verbose_name='组类型')),
                ('status', models.CharField(db_index=True, default='active', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='system.sysorggroup')),
            ],
            options={
                'verbose_name': '组织/组',
                'verbose_name_plural': '组织/组',
                'db_table': 'sys_org_group',
            },
        ),
        migrations.CreateModel(
            name='SysPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_code', models.CharField(max_length=128, unique=True, verbose_name='权限编码')),
                ('perm_name', models.CharField(max_length=128, verbose_name='权限名称')),
                ('resource_type', models.CharField(choices=[('menu', '菜单'), ('api', '接口'), ('button', '按钮'), ('data_scope', '数据范围')], default='api', max_length=32, verbose_name='资源类型')),
            ],
            options={
                'verbose_name': '权限点',
                'verbose_name_plural': '权限点',
                'db_table': 'sys_permission',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=32, unique=True, verbose_name='角色编码')),
                ('role_name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysReviewerWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('leave', '请假审核'), ('dev_audit', '开发审核'), ('close_audit', '关闭审核')], db_index=True, max_length=32, verbose_name='审核类型')),
                ('module_code', models.CharField(blank=True, max_length=64, verbose_name='模块编码')),
                ('status', models.CharField(default='active', max_length=16)),
                ('reviewer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_whitelists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '审核白名单',
                'verbose_name_plural': '审核白名单',
                'db_table': 'sys_reviewer_whitelist',
            },
        ),
        migrations.CreateModel(
            name='SysUserGroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_group', models.BooleanField(default=False, verbose_name='是否主组')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_roles', to='system.sysorggroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_roles', to='system.sysrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户-组-角色',
                'verbose_name_plural': '用户-组-角色',
                'db_table': 'sys_user_group_role',
                'unique_together': {('user', 'group', 'role')},
            },
        ),
        migrations.CreateModel(
            name='SysRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='system.syspermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='system.sysrole')),
            ],
            options={
                'verbose_name': '角色-权限',
                'verbose_name_plural': '角色-权限',
                'db_table': 'sys_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
