# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchCompensationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('control', '管控'), ('special', '专项'), ('designated', '指定')], max_length=16, verbose_name='转单类型')),
                ('compensation_type', models.CharField(choices=[('extra_ticket', '转单人补单'), ('update_receive_time', '更新接单时间'), ('skip_next', '跳过下次接单')], max_length=32, verbose_name='补偿类型')),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '转单补偿记录',
                'verbose_name_plural': '转单补偿记录',
                'db_table': 'dispatch_compensation_record',
            },
        ),
        migrations.CreateModel(
            name='DispatchCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_scene', models.CharField(choices=[('day', '白班大循环'), ('kernel', '内核'), ('control', '管控'), ('special', '专项')], db_index=True, max_length=32, verbose_name='业务场景')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '轮询游标',
                'verbose_name_plural': '轮询游标',
                'db_table': 'dispatch_cursor',
            },
        ),
        migrations.CreateModel(
            name='DispatchDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_path_json', models.JSONField(blank=True, null=True, verbose_name='决策路径')),
                ('fallback_reason', models.CharField(blank=True, max_length=256, verbose_name='兜底原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': '分单决策日志',
                'verbose_name_plural': '分单决策日志',
                'db_table': 'dispatch_decision_log',
            },
        ),
        migrations.CreateModel(
            name='DispatchPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_code', models.CharField(max_length=64, unique=True, verbose_name='策略编码')),
                ('policy_name', models.CharField(max_length=128, verbose_name='策略名称')),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('effective_from', models.DateTimeField(blank=True, null=True, verbose_name='生效开始')),
                ('effective_to', models.DateTimeField(blank=True, null=True, verbose_name='生效结束')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
            ],
            options={
                'verbose_name': '分单策略',
                'verbose_name_plural': '分单策略',
                'db_table': 'dispatch_policy',
            },
        ),
        migrations.CreateModel(
            name='DispatchRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=64, verbose_name='规则编码')),
                ('priority_no', models.PositiveIntegerField(default=0, verbose_name='优先级(越小越先)')),
                ('condition_expr', models.JSONField(blank=True, null=True, verbose_name='条件表达式')),
                ('action_type', models.CharField(db_index=True, max_length=64, verbose_name='动作类型')),
                ('action_param_json', models.JSONField(blank=True, null=True, verbose_name='动作参数')),
                ('status', models.CharField(default='active', max_length=16)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='dispatch.dispatchpolicy')),
            ],
            options={
                'verbose_name': '分单规则',
                'verbose_name_plural': '分单规则',
                'db_table': 'dispatch_rule',
            },
        ),
    ]
