# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty', '0001_initial'),
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchdecisionlog',
            name='final_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_decision_as_final', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchdecisionlog',
            name='hit_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='dispatch.dispatchrule'),
        ),
        migrations.AddField(
            model_name='dispatchdecisionlog',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='dispatch.dispatchpolicy'),
        ),
        migrations.AddField(
            model_name='dispatchdecisionlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_decisions', to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='dispatchcursor',
            name='current_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_cursors', to='duty.dutyschedulemember'),
        ),
        migrations.AddField(
            model_name='dispatchcursor',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_cursors', to='duty.dutyschedule'),
        ),
        migrations.AddField(
            model_name='dispatchcompensationrecord',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_comp_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchcompensationrecord',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_compensations', to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='dispatchcompensationrecord',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_comp_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dispatchrule',
            index=models.Index(fields=['policy', 'priority_no', 'status'], name='dispatch_ru_policy__bf1bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchdecisionlog',
            index=models.Index(fields=['ticket', 'created_at'], name='dispatch_de_ticket__ed6593_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dispatchcursor',
            unique_together={('schedule', 'biz_scene')},
        ),
    ]
