# Generated by Django 3.2.25 on 2026-04-07 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identities', models.CharField(blank=True, help_text='逗号分隔：管控control、bu、ops、dev、guest', max_length=64, verbose_name='业务身份')),
                ('w3_subject', models.CharField(blank=True, db_index=True, help_text='接入 W3 后填写；预留', max_length=256, verbose_name='W3 外部标识')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
