# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_date', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('day_type', models.CharField(choices=[('workday', '工作日'), ('weekend', '周末'), ('holiday', '法定节假日')], db_index=True, max_length=16, verbose_name='日类型')),
                ('shift_type', models.CharField(choices=[('day', '白班'), ('night', '夜班')], default='day', max_length=16, verbose_name='班次类型')),
            ],
            options={
                'verbose_name': '值班日历',
                'verbose_name_plural': '值班日历',
                'db_table': 'duty_calendar',
            },
        ),
        migrations.CreateModel(
            name='DutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_code', models.CharField(max_length=64, unique=True, verbose_name='值班表编码')),
                ('schedule_name', models.CharField(max_length=128, verbose_name='值班表名称')),
                ('schedule_type', models.CharField(choices=[('kernel', '内核'), ('control', '管控'), ('public_cloud', '公有云'), ('special', '专项')], db_index=True, max_length=32, verbose_name='值班表类型')),
                ('applicable_day_type', models.CharField(choices=[('workday', '工作日'), ('night', '夜班'), ('holiday', '节假日'), ('all', '全部')], default='all', max_length=16, verbose_name='适用日类型')),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
            ],
            options={
                'verbose_name': '值班表',
                'verbose_name_plural': '值班表',
                'db_table': 'duty_schedule',
            },
        ),
        migrations.CreateModel(
            name='DutyScheduleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.PositiveIntegerField(default=0, verbose_name='轮询顺序')),
                ('weight', models.PositiveSmallIntegerField(default=1, verbose_name='权重')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '值班成员',
                'verbose_name_plural': '值班成员',
                'db_table': 'duty_schedule_member',
                'ordering': ['schedule_id', 'order_no'],
            },
        ),
        migrations.CreateModel(
            name='DutySubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '调班/代班',
                'verbose_name_plural': '调班/代班',
                'db_table': 'duty_substitution',
            },
        ),
        migrations.CreateModel(
            name='LeaveApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '拒绝')], max_length=16, verbose_name='动作')),
                ('comment', models.TextField(blank=True, verbose_name='意见')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '请假审批记录',
                'verbose_name_plural': '请假审批记录',
                'db_table': 'leave_approval_record',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, max_length=32, verbose_name='请假类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=16, verbose_name='审批状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '请假申请',
                'verbose_name_plural': '请假申请',
                'db_table': 'leave_request',
            },
        ),
    ]
