# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='applicant_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapprovalrecord',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='duty.leaverequest'),
        ),
        migrations.AddField(
            model_name='leaveapprovalrecord',
            name='reviewer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approval_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutysubstitution',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_substitutions_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutysubstitution',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='duty.dutyschedule'),
        ),
        migrations.AddField(
            model_name='dutysubstitution',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_substitutions_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dutyschedulemember',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='duty.dutyschedule'),
        ),
        migrations.AddField(
            model_name='dutyschedulemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedule_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dutyschedulemember',
            index=models.Index(fields=['schedule', 'order_no'], name='duty_schedu_schedul_883aad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dutyschedulemember',
            unique_together={('schedule', 'user')},
        ),
    ]
