# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(db_index=True, max_length=128, verbose_name='配置键')),
                ('before_json', models.JSONField(blank=True, null=True, verbose_name='变更前')),
                ('after_json', models.JSONField(blank=True, null=True, verbose_name='变更后')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '配置审计日志',
                'verbose_name_plural': '配置审计日志',
                'db_table': 'config_audit_log',
            },
        ),
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=128, verbose_name='配置键')),
                ('item_name', models.CharField(max_length=128, verbose_name='配置名称')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('bool', '布尔'), ('json', 'JSON')], default='string', max_length=16, verbose_name='值类型')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '配置项',
                'verbose_name_plural': '配置项',
                'db_table': 'config_item',
            },
        ),
        migrations.CreateModel(
            name='ConfigNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace_code', models.CharField(max_length=64, unique=True, verbose_name='命名空间编码')),
                ('namespace_name', models.CharField(max_length=128, verbose_name='命名空间名称')),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'verbose_name': '配置命名空间',
                'verbose_name_plural': '配置命名空间',
                'db_table': 'config_namespace',
            },
        ),
        migrations.CreateModel(
            name='ConfigPublishRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '配置发布记录',
                'verbose_name_plural': '配置发布记录',
                'db_table': 'config_publish_record',
            },
        ),
        migrations.CreateModel(
            name='ConfigValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_value_json', models.JSONField(blank=True, null=True, verbose_name='配置值')),
            ],
            options={
                'verbose_name': '配置值',
                'verbose_name_plural': '配置值',
                'db_table': 'config_value',
            },
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('offline', '已下线')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='config_center.confignamespace')),
            ],
            options={
                'verbose_name': '配置版本',
                'verbose_name_plural': '配置版本',
                'db_table': 'config_version',
            },
        ),
    ]
