# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_versions_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configvalue',
            name='config_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='config_center.configitem'),
        ),
        migrations.AddField(
            model_name='configvalue',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='config_center.configversion'),
        ),
        migrations.AddField(
            model_name='configpublishrecord',
            name='from_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publish_records_from', to='config_center.configversion'),
        ),
        migrations.AddField(
            model_name='configpublishrecord',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_records', to='config_center.confignamespace'),
        ),
        migrations.AddField(
            model_name='configpublishrecord',
            name='operator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_publish_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configpublishrecord',
            name='to_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_records_to', to='config_center.configversion'),
        ),
        migrations.AddField(
            model_name='configitem',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='config_center.confignamespace'),
        ),
        migrations.AddField(
            model_name='configauditlog',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='config_center.confignamespace'),
        ),
        migrations.AddField(
            model_name='configauditlog',
            name='operator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='config_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='configvalue',
            unique_together={('version', 'config_item')},
        ),
        migrations.AlterUniqueTogether(
            name='configitem',
            unique_together={('namespace', 'item_key')},
        ),
    ]
