# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsStageFunnelDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('from_stage_code', models.CharField(db_index=True, max_length=64, verbose_name='来源阶段')),
                ('to_stage_code', models.CharField(db_index=True, max_length=64, verbose_name='目标阶段')),
                ('transfer_count', models.PositiveIntegerField(default=0, verbose_name='流转次数')),
                ('transfer_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='流转比例')),
            ],
            options={
                'verbose_name': '阶段漏斗日汇总',
                'verbose_name_plural': '阶段漏斗日汇总',
                'db_table': 'ads_stage_funnel_daily',
            },
        ),
        migrations.CreateModel(
            name='AdsTicketKpiDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('ticket_count', models.PositiveIntegerField(default=0, verbose_name='工单数')),
                ('closed_count', models.PositiveIntegerField(default=0, verbose_name='关闭数')),
                ('sla_ontime_count', models.PositiveIntegerField(default=0, verbose_name='SLA准时数')),
                ('avg_close_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='平均闭环分钟')),
            ],
            options={
                'verbose_name': '工单KPI日汇总',
                'verbose_name_plural': '工单KPI日汇总',
                'db_table': 'ads_ticket_kpi_daily',
            },
        ),
    ]
