# Generated by Django 4.2.22 on 2026-04-04 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsticketkpidaily',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_ticket_kpi_daily', to='system.sysorggroup'),
        ),
        migrations.AddField(
            model_name='adsticketkpidaily',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads_ticket_kpi_daily', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adsstagefunneldaily',
            index=models.Index(fields=['stat_date', 'from_stage_code', 'to_stage_code'], name='ads_stage_f_stat_da_c2d5ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adsticketkpidaily',
            unique_together={('stat_date', 'group', 'user')},
        ),
    ]
