# Generated by Django 3.2.25 on 2026-04-07 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import tickets.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, editable=False, unique=True, verbose_name='单号')),
                ('stage', models.CharField(choices=[('hcs_submit', 'HCS提单'), ('issue_review', '问题审核'), ('ops_analysis', '运维人员分析'), ('dev_analysis', '开发人员分析'), ('dev_review', '开发人员审核'), ('ops_closure', '运维人员闭环'), ('audit_close', '问题审核关闭')], db_index=True, default='hcs_submit', max_length=32, verbose_name='阶段')),
                ('title', models.CharField(max_length=512, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_self_service', models.BooleanField(default=False, verbose_name='运维自提单')),
                ('extra_data', tickets.fields.JSONTextField(blank=True, default=dict, verbose_name='阶段字段(JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='当前处理人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_tickets', to=settings.AUTH_USER_MODEL, verbose_name='提单人')),
            ],
            options={
                'verbose_name': '运维单',
                'verbose_name_plural': '运维单',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=32, verbose_name='来源阶段')),
                ('to_stage', models.CharField(max_length=32, verbose_name='目标阶段')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='tickets.ticket', verbose_name='工单')),
            ],
            options={
                'verbose_name': '阶段变更记录',
                'verbose_name_plural': '阶段变更记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
